// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-hfdzyxUx_RUO9W6JmU0ddmJFk7MVFA',
    appId: '1:784114978264:web:5993e97273c2d103f3b6ad',
    messagingSenderId: '784114978264',
    projectId: 'chatapp-9d7e8',
    authDomain: 'chatapp-9d7e8.firebaseapp.com',
    storageBucket: 'chatapp-9d7e8.appspot.com',
    measurementId: 'G-C3474S1X3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1YLWT8cE7s-qD5Yg__or-JEOO31OC3Bc',
    appId: '1:784114978264:android:c00de0f4b2a9ccf3f3b6ad',
    messagingSenderId: '784114978264',
    projectId: 'chatapp-9d7e8',
    storageBucket: 'chatapp-9d7e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPu4vug9EyA9fkiCX2gLweyCGXrWPnyuE',
    appId: '1:784114978264:ios:7b1295a11cd7709cf3b6ad',
    messagingSenderId: '784114978264',
    projectId: 'chatapp-9d7e8',
    storageBucket: 'chatapp-9d7e8.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPu4vug9EyA9fkiCX2gLweyCGXrWPnyuE',
    appId: '1:784114978264:ios:7b1295a11cd7709cf3b6ad',
    messagingSenderId: '784114978264',
    projectId: 'chatapp-9d7e8',
    storageBucket: 'chatapp-9d7e8.appspot.com',
    iosBundleId: 'com.example.untitled5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9-hfdzyxUx_RUO9W6JmU0ddmJFk7MVFA',
    appId: '1:784114978264:web:6a77acb6044009aef3b6ad',
    messagingSenderId: '784114978264',
    projectId: 'chatapp-9d7e8',
    authDomain: 'chatapp-9d7e8.firebaseapp.com',
    storageBucket: 'chatapp-9d7e8.appspot.com',
    measurementId: 'G-GNZ0CZGYPD',
  );
}
